server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr
  redis:
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
